# Generated by Django 4.0.3 on 2022-07-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aadress',
            new_name='address',
        ),
    ]
