# Generated by Django 4.0.3 on 2022-04-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_country_alter_address_options_book_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='country',
            new_name='published_countries',
        ),
    ]
