# Generated by Django 4.0.3 on 2022-06-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('review_message', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
