# Generated by Django 4.0.3 on 2022-06-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_message',
            field=models.TextField(max_length=200),
        ),
    ]
