# Generated by Django 4.0.3 on 2022-07-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_category_author_about_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_time',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
