# Generated by Django 4.0.3 on 2022-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0014_alter_book_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='book_app.category'),
        ),
    ]
