# Generated by Django 4.0.3 on 2022-07-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='editors_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
