# Generated by Django 4.0.3 on 2022-07-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_alter_book_description_alter_book_editors_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
