# Generated by Django 4.0.3 on 2022-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0018_book_book_image_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='static/images/about-img.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/images/about-img.png', upload_to='uploads'),
        ),
    ]
