# Generated by Django 4.0.3 on 2022-07-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0024_alter_savedbookmodel_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbookmodel',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedbook', to='book_app.book'),
        ),
    ]
