# Generated by Django 4.0.3 on 2022-07-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0026_alter_savedbookmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Restocked', 'Restocked')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='minquantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity_instock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
