# Generated by Django 4.0.3 on 2022-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0027_book_amount_book_available_book_minquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='minquantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
