# Generated by Django 4.0.3 on 2022-07-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0029_alter_book_quantity_instock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
