# Generated by Django 4.0.3 on 2022-07-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0032_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_countries',
            field=models.ManyToManyField(blank=True, to='book_app.country'),
        ),
    ]
