# Generated by Django 4.1 on 2022-08-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0034_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
