# Generated by Django 4.1 on 2022-08-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0035_review_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
