# Generated by Django 4.0.3 on 2022-07-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='state',
        ),
    ]
